image:
  - Visual Studio 2019

install:
  - cmd: C:\Python37\python.exe -m pip install -r requirements.txt

build: Script

build_script:
  - cmd: C:\Python37\Scripts\pyinstaller.exe -F main.py

artifacts:
  - path: dist\main.exe
    name: mcdiscc-resource-builder
