image:
  - Visual Studio 2019

install:
  - cmd: C:\Python37\python.exe -m pip install -r requirements.txt

build: Script

build_script:
  - cmd: C:\Python37\Scripts\pyinstaller.exe -F main.py
  - cmd: copy release\windows\ffmpeg\*.exe dist\
  - ps: Compress-Archive -Path dist -DestinationPath mcdisc-resource-builder.zip

artifacts:
  - path: mcdisc-resource-builder.zip
    name: mcdisc-resource-builder
